imaNNeo/fl_chart

lib/src/chart/bar_chart/bar_chart_painter.dart, lib/src/chart/line_chart/line_chart_painter.dart, lib/src/chart/pie_chart/pie_chart_painter.dart
#15 enabled pie chart repainting
=> enabled pie chart repainting

lib/src/chart/bar_chart/bar_chart_data.dart, lib/src/chart/base/axis_chart/axis_chart_data.dart, lib/src/chart/base/axis_chart/axis_chart_painter.dart, lib/src/chart/line_chart/line_chart_data.dart
added backgroundColor property to AxisChartData which is used in the AxisChartPainter to draw a colored rect that fills the chart
BarChartData and LineChartData are passing the backgroundColor to its super class AxisChartData
=> added backgroundColor (initial)

lib/src/chart/line_chart/line_chart_painter.dart
This fixes an issue where BelowBar ignored `gradientColorStops` property and used `colorStops` from the bar itself. Should fix #46
=> (fix) BelowBar considers its own color stops refs #46

lib/src/chart/bar_chart/bar_chart.dart, lib/src/chart/line_chart/line_chart.dart, lib/src/chart/pie_chart/pie_chart.dart
Fix [issue 100](https://github.com/imaNNeoFighT/fl_chart/issues/100). 
RenderBox.size should not be used when building the layout.
=> Replased containerRenderBox.size to containerRenderBox.constraints.biggest

lib/src/chart/line_chart/line_chart_data.dart, lib/src/chart/line_chart/line_chart_painter.dart, repo_files/documentations/line_chart.md
I needed a way to show low and high values on the chart so I modified `LineChartBarData` implementation to support `gradientFrom` and `gradientTo` parameters based on similar logic from `BarAreaData` implementation.
With those changes making charts like the one in attachment is possible.
=> Gradient direction support on line chart

lib/src/chart/bar_chart/bar_chart.dart, lib/src/chart/bar_chart/bar_chart_painter.dart, lib/src/chart/base/axis_chart/axis_chart_painter.dart, lib/src/chart/base/base_chart/base_chart_painter.dart, lib/src/chart/line_chart/line_chart.dart, lib/src/chart/line_chart/line_chart_painter.dart, lib/src/chart/pie_chart/pie_chart.dart, lib/src/chart/pie_chart/pie_chart_painter.dart, lib/src/chart/scatter_chart/scatter_chart.dart, lib/src/chart/scatter_chart/scatter_chart_painter.dart
All painters should use the text scale factor when drawing text. Since there is no context in the chart painters available, we have to inject it during the creation of each painter.
=> respect text scale factor when drawing text

example/lib/line_chart/samples/line_chart_sample8.dart, lib/src/chart/line_chart/line_chart_data.dart, lib/src/chart/line_chart/line_chart_painter.dart
This is an addition to the touchline. Setting the bool to `true` will stop it at the top of the chart instead of at the dot.
=> Feature: full height touchline

repo_files/documentations/bar_chart.md, repo_files/documentations/line_chart.md
Fixed links in documents.
I guess the syntax of these links were the opposite.
=> Fix RangeAnnotations links in doc

lib/src/chart/line_chart/line_chart_painter.dart
Fixes situation where the tooltip, having set fitInsideTheChart, goes above or below the chart area.
Was:
Is:
=> Fix for fitInsideTheChart when tooltip is below or above the chart area

lib/src/chart/bar_chart/bar_chart_data.dart, lib/src/chart/bar_chart/bar_chart_painter.dart, lib/src/chart/line_chart/line_chart_data.dart, lib/src/chart/line_chart/line_chart_painter.dart, repo_files/documentations/bar_chart.md, repo_files/documentations/line_chart.md
This PR provides a fix for #225
Also fixes a minor renaming bug that was in PR #236 
Changes added -
Added new parameter fitInsideVertically to BarTouchTooltipData and LineTouchTooltipData for fitting the tooltip vertically inside the charts.
Renamed fitInsideTheChart to fitInsideHorizontally to avoid confusion.
=> Added fitInsideVertically support for bar chart and line chart tooltips.

lib/src/chart/bar_chart/bar_chart_data.dart, lib/src/chart/bar_chart/bar_chart_painter.dart, lib/src/chart/line_chart/line_chart_data.dart, lib/src/chart/line_chart/line_chart_painter.dart, repo_files/documentations/bar_chart.md, repo_files/documentations/line_chart.md
This is a copy of PR #237 for the dev branch
This PR provides a fix for #225 
Changes added -
1. Added new parameter fitInsideVertically to BarTouchTooltipData and LineTouchTooltipData for fitting the tooltip vertically inside the charts.
2. Renamed fitInsideTheChart to fitInsideHorizontally to avoid confusion.
3. Updated documentation.
=> Added fitInsideVertically support for bar chart and line chart tooltips

README.md, repo_files/documentations/bar_chart.md, repo_files/documentations/handle_animations.md, repo_files/documentations/handle_touches.md, repo_files/documentations/line_chart.md, repo_files/documentations/pie_chart.md, repo_files/documentations/scatter_chart.md
The code blocks are now highlighted correctly, whereas before there was no syntax highlighting or wrong syntax highlighting.
=> Fix code blocks highlighting

example/lib/line_chart/samples/line_chart_sample3.dart, lib/src/chart/line_chart/line_chart_data.dart, lib/src/chart/line_chart/line_chart_painter.dart, test/chart/data_pool.dart
Like the GetDotColorCallback that contains the barData parameter, it's usefull to pass it also to the checkToShowDot function. In my case I needed to know the index position of the spot for example. That was not possible to find out while lerp-ing (animation).
=> Adding barData parameter to checkToShowDot Function

example/lib/pie_chart/samples/pie_chart_sample2.dart, lib/src/chart/pie_chart/pie_chart_painter.dart
When using `PieChartData`'s `startDegreeOffset`, it can happen a section spans across the 0 degrees point. 
In such a case, the aforementioned section will not be detected if touched on its "positive" side as the code assumes `fromDegree` will always be lower than `toDegree` (which would not be true here, angles being constrained in the [0:359] range).
This PR fixes this issue by considering the `relativeTouchAngle` which is the touch angle relative to the first section (whatever the `startDegreeOffset` might be). This approach keeps the code simple and now guarantees `fromDegree` will always be smaller than `toDegree`.
=> Fix touch detection of sections spanned across the 0 degrees point

lib/src/chart/line_chart/line_chart_painter.dart
This PR fixes an issue where line chart fails to render if there's more than one `FlSpot` with null *x* or *y* in a row.
If there are two null spots in a row, then two empty lists will be added to `barList`. Next non-null spot will be added to the second one leaving an empty list in `barList` and causing rendering error.
=> Fix spot split when more than one in a row is null

lib/src/chart/line_chart/line_chart_data.dart
Current logic assumes that first spot in the chart data is never null. In case it's missing e.g. *x* value then `maxX` is initialized with `null` and this part of code tries to compare spot value to it and throws NPE:
``` Dart
// Same for minX, minY and maxY
if (canModifyMaxX && spot.x > maxX) {
maxX = spot.x;
}
```
=> Fix filling chart bounds

lib/src/chart/pie_chart/pie_chart.dart
Using pieChart in ListView causes the exception "setState() called after dispose()"
=> Fix the setState issue using PieChart in the ListView

lib/src/chart/pie_chart/pie_chart.dart
Fixes `Another exception was thrown: A build function returned null.` when creating a PieChart
=> Fixes 'Build function can not return null'

example/lib/bar_chart/samples/bar_chart_sample3.dart, lib/src/chart/bar_chart/bar_chart_data.dart, lib/src/chart/bar_chart/bar_chart_painter.dart, lib/src/chart/line_chart/line_chart_data.dart, lib/src/chart/line_chart/line_chart_painter.dart, repo_files/documentations/bar_chart.md, repo_files/documentations/line_chart.md, test/chart/data_pool.dart
Hi @imaNNeoFighT, I'm proposing this change, but happy to take any feedback.
- The main purpose is to allow people to choose where to draw the tooltip for BarChart instead of fully tied to whether the value is positive.
- Since the tooltip can draw on either top or bottom of the bar, the `tooltipBottomMargin` doesn't makes sense, so I'm introducing a breaking change to rename it.
- At the same time, rename the `tooltipBottomMargin` for LineChart too, so that we can allow drawing tooltip on bottom for LineChart in future. Think about the example 4 (reverse chart).
=> Control bar chart tooltip direction.

lib/src/chart/radar_chart/radar_chart_painter.dart
issue #627 has been fixed.
radar chart now can draw the circular border data.
``` dart
RadarChartData(
dataSets: showingDataSets(),
radarBorderData: const BorderSide(color: Colors.transparent),
...
),
```
=> fix issue #627

lib/src/utils/utils.dart
There are two definitions for the number billion (in short scale and in long scale) as stated in https://en.wikipedia.org/wiki/Billion
=> specify that it uses the short scale for bilions

example/lib/line_chart/samples/line_chart_sample1.dart
This library is fantastic.  But I thought the samples were room for improvement because there were many classes and arguments in this library.
First, that developers who use this library should want to know about this library.
So they don't have to see codes unrelated to this library(For example, StatefulWidget, AspectRatio, and so on).
In other words, I think the codes about this library are better if on the top of the sample.
Then, I think the sample codes are better if divided into smaller functions because this library can do many excellent jobs.
I tried to refactor it. I think it's easier to read than before. What do you think?
=> Refactoring line_chart_sample_1

CHANGELOG.md, lib/src/chart/base/line.dart, lib/src/chart/pie_chart/pie_chart_painter.dart, test/chart/base/line_test.dart, test/chart/data_pool.dart
Fixes #818.
Currently, we use this logic to add a separator between PieChart sections:
We draw each section and fill them. Then we remove some lines from the canvas to make the distance between sections. It breaks the stroke. Because we remove a line from the sections.
Now we make a path and draw each section with space by default. And there is no need to remove anything from the canvas. 
Then stroke should work fine now.
=> Fix pie chart stroke problem when adding space between sections (using new approach), #818.

CHANGELOG.md, lib/src/chart/line_chart/line_chart_painter.dart
Continue of #644 PR Opened by @PerLycke.
desctiption:
> Previously it returned the first occurrence of a spot within the threshold, and not the nearest, which I understand is the purpose of this function.
With the updated function the user is able to set the threshold to a big number (like double.maxFinite) and get the nearest spot from this function. This behaviour (clicking anywhere and get the nearest spot) is seen in e.g. charts_flutter.
AFAIK this shouldn't break anything for existing users, just fix / add the above functionality.
Fixes #641, #645.
=> Fix getNearestTouchedSpot

 .codecov.yml
In other to improve the test coverage, we should remove the example directory
because we don't want that also the example enter inside the scoring.
In addition, this improves the GitHub workflows related to the upload of the action, if you like to use this proposal you need to post your codecov secret inside the GitHub action.
Please let me know if you want that I restore the old version of the GitHub workflow
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>
=> ci: improve codecov configuration

CHANGELOG.md, lib/src/chart/scatter_chart/scatter_chart_data.dart, lib/src/chart/scatter_chart/scatter_chart_painter.dart, test/chart/data_pool.dart, test/chart/scatter_chart/scatter_chart_painter_test.dart
#897.
The Scatter chart can be used as a Bubble chart by providing different radii. So, when the radius is bigger and close to the axis of the chart, it is used to cross the axis and go out of the chart.
So, in my approach, I've added a new attribute in `ScatterChartData` called `clipBubble`. If we set it to true, it will clip the chart before drawing the spots such that the bubbles never cross the chart's axes. After the bubbles are drawn, it again restores the original region.
=> Implement `clipData` feature in scatter chart.

CHANGELOG.md, lib/src/chart/line_chart/line_chart_data.dart, lib/src/chart/line_chart/line_chart_painter.dart, repo_files/documentations/line_chart.md, test/chart/data_pool.dart, test/chart/line_chart/line_chart_painter_test.dart, test/chart/line_chart/line_chart_painter_test.mocks.dart, test/chart/line_chart/line_chart_renderer_test.mocks.dart
Instead of only considering the distance on the x axis when checking for the closest spot, this feature allows to choose the closest spot based on Euclidean distance
TODO: 
Fixes #716, #261
=> Add option to include y distance for nearest touched spot

lib/src/chart/scatter_chart/scatter_chart_data.dart, lib/src/chart/scatter_chart/scatter_chart_painter.dart, test/chart/data_pool.dart, test/chart/scatter_chart/scatter_chart_data_test.dart, test/chart/scatter_chart/scatter_chart_painter_test.dart, test/chart/scatter_chart/scatter_chart_renderer_test.mocks.dart
fix #902 
1. Allows giving `label` to `ScatterSpot` in Scatter Chart.
2. Draws the label based on the `ScatterLabelSettings` provided.
=> Label feature in Scatter Chart

CHANGELOG.md, pubspec.yaml
* **BUGFIX** Fix drawing BetweenBarsArea problem when there are `nullSpots` in fromLine and toLine, #912.
* **FEATURE** Allow to have vertically grouped BarChart using `fromY` and `toY` properties in [BarChartRodData](https://github.com/imaNNeoFighT/fl_chart/blob/feature/multi-rods-on-bar-chart/repo_files/documentations/bar_chart.md#BarChartRodData) It means you can have a negative and a positive bar chart at the same X location. #334, #875. Check [BarChartSample5](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#sample-5-source-code) and [BarChartSample6](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#sample-6-source-code.
* **BREAKING** Renamed `y` property to `toY` in …
=> Bump version to 0.46.0

CHANGELOG.md, pubspec.yaml
**This release has some breaking changes. So please check out the migration guide [here](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/migration_guides/MIGRATION_00_50_00.md)**
* **IMPROVEMENT** Allow to return a Widget in [SideTitles.getTitlesWidget](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles) instead of a `String`. For example, you can pass an [Icon](https://api.flutter.dev/flutter/widgets/Icon-class.html) widget as a title, #183. Check below samples:
> **LineChartSample 8** ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample8.dart))
> <img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_c …
=> Bump version to 0.50.0

CHANGELOG.md, pubspec.yaml
* **BUGFIX** Allow to show axisTitle without sideTitles, #963
=> Bump version to 0.50.1

CHANGELOG.md, lib/src/chart/line_chart/line_chart_painter.dart, test/chart/line_chart/line_chart_painter_test.dart, test/chart/line_chart/line_chart_painter_test.mocks.dart, test/chart/line_chart/line_chart_renderer_test.mocks.dart, test/chart/pie_chart/pie_chart_renderer_test.mocks.dart
Fixes order of drawing lineChart bar indicators (from behind to front), #198.
**Before:**
**After:**
=> Fix order of drawing lineChart indicators

CHANGELOG.md, pubspec.yaml
* **IMPROVEMENT** Fix order of drawing lineChart bar indicator problem, #198.
* **FEATURE** Add `isStrokeJoinRound` property in [LineChartBarData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartbardata).
* **IMPROVEMENT** Upgrade to Flutter 3, #997.
* **FEATURE** Add `chartRendererKey` property to the [LineChart](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md), [BarChart](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md), and [ScatterChart](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/scatter_chart.md). We pass it directly to our chart renderers that are responsible to render the chart itself (without anything …
=> Bump version to 0.50.3

CHANGELOG.md, pubspec.yaml
* **FEATURE** (by @imaNNeoFighT): Add `SideTitleWidget` to help you use it in [SideTitles.getTitlesWidget]. It's a wrapper around your widget. It keeps your provided `child` widget close to the chart. It has `angle` and `space` properties to handle margin and rotation. There is a `axisSide` property that you should fill, it has provided to you in the MetaData object. Check the below sample:
```dart
getTitlesWidget: (double value, TitleMeta meta) {
return SideTitleWidget(
axisSide: meta.axisSide,
space: 8.0,
angle: 0.0,
child: const Text("This is your widget"),
);
},
```
* **IMPROVEMENT** (by @imaNNeoFighT): Fix default LineChart interval issue on small view sizes, #909.
=> Bump version to 0.51.0

CHANGELOG.md, lib/src/chart/radar_chart/radar_chart_data.dart, lib/src/chart/radar_chart/radar_chart_painter.dart, repo_files/documentations/radar_chart.md, test/chart/radar_chart/radar_chart_data_test.dart, test/chart/radar_chart/radar_chart_painter_test.dart
Use it like this : 
```dart
RadarChart(
RadarChartData(
...,
radarShape: RadarShape.polygon, // nullable arg defaulting to RadarShape.circle
),
)
```
| **Polygon**                                                                                                     | **Circle** (now default / previously the only one)                                                              |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/32898426/172429103-a7adef6b-2212-4c5e-9c2b-a28c15d55285.png) | ![image](https://user-images.githubusercontent.com/32898426/172429209-1a65 …
=> Add the ability to select the RadarChart shape (circle or polygon)

CHANGELOG.md, lib/src/chart/radar_chart/radar_chart_painter.dart
Fixes an issue where titles are displayed at an uneven distance from a RadarChart when titlePositionPercentageOffset is used.
Resolves #1074
=> fix: Uneven titles in RadarChart

CHANGELOG.md, lib/src/chart/radar_chart/radar_chart_painter.dart
If the max and min values in a RadarDataSet are equal, the `drawTicks` method in `radar_chart_painter.dart` will enter an infinite loop.
This is due to a for loop that fails to be incremented if the max and min values are equal, causing the loop to never meet its exit condition.
I have replaced the for loop with one that will always exit.
Resolves #882
=> fix: RadarChart crashes if all values in RadarDataSet are equal

CHANGELOG.md, pubspec.yaml
* **BUGFIX** (by @ateich): Fix infinite loop in RadarChart when all values in RadarDataSet are equal, #882.
* **BUGFIX** (by @ateich): Fix uneven titles in RadarChart when using titlePositionPercentageOffset, #1074.
* **BUGFIX** (by @imaNNeoFighT): Fix PieChart single section stroke issue, #1089
=> Bump version to 0.55.1

repo_files/documentations/line_chart.md
fixed small typo in docs, missing a word
=> fix: small typo in docs

CHANGELOG.md, lib/src/chart/radar_chart/radar_chart_data.dart, lib/src/chart/radar_chart/radar_chart_painter.dart, repo_files/documentations/radar_chart.md
Hello.
We are using your wonderful project.
When using RadarChart in our project, we had a request to set the titlePositionPercentageOffset per Title.
When we have long titles in RadarChart, we had a problem with too much space between the top and bottom titles and RadarChart, as shown in the attached image.
Therefore, we added a positionPercentageOffset parameter to RadarChartTitle to allow setting the titlePositionPercentageOffset individually.
By doing so, the title position can now be adjusted individually, as shown in the following image.
=> Added ability to set titlePositionPercentageOffset for individual RadarChartTitle

CHANGELOG.md, lib/src/chart/bar_chart/bar_chart_data.dart
Remove assertion to check to provide only one of `color` or `gradient` property in the [BarChartRodData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/bar_chart.md#barchartroddata) and [BackgroundBarChartRodData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/bar_chart.md#backgroundbarchartroddata).
=> Remove assertion to check provide only one of `color` or `gradient`

example/lib/presentation/samples/line/line_chart_sample11.dart
=> Fix lineChartSample11 two line titles issue

.gitignore, CHANGELOG.md, example/lib/presentation/samples/line/line_chart_sample3.dart, lib/src/chart/base/axis_chart/axis_chart_data.dart, lib/src/chart/base/axis_chart/axis_chart_helper.dart, lib/src/chart/base/axis_chart/axis_chart_widgets.dart, lib/src/chart/base/axis_chart/side_titles/side_titles_widget.dart, repo_files/documentations/base_chart.md, test/chart/base/axis_chart/axis_chart_data_test.dart, test/chart/base/axis_chart/axis_chart_helper_test.dart, test/chart/base/axis_chart/axis_chart_widgets_test.dart, test/chart/data_pool.dart
Hi All!
I'm adding a feature to add an option for SideTitle to be fitted inside its corresponding axis bounding box.
This will fix #603. Below is the illustration:
- Before Using FitInside (SideTitle is overflowed): 
- After Using FitInside (SideTitle is translated, hence not overflowed):
What is added:
- FitInside data class (SideTitleFitInsideData) in lib/src/chart/base/axis_chart/axis_chart_data.dart
- FitInside parameter on SideTitleWidget
- Test for data class (SideTitleFitInsideData)
- Sample usage in example/lib/presentation/samples/line/line_chart_sample3.dart
=> FEATURE: Fit SideTitle inside axis bounding box (prevent title overflow on edge)

repo_files/documentations/base_chart.md
It is true since 6328ddc95e472aa4b627f00bf46c2d6a11e72e6e.
=> docs(FlGridData): correct default value of drawVerticalLine

CHANGELOG.md, pubspec.yaml
* **IMPROVEMENT** (by @imaNNeo) Remove assertion to check to provide only one of `color` or `gradient` property in the [BarChartRodData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/bar_chart.md#barchartroddata) and [BackgroundBarChartRodData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/bar_chart.md#backgroundbarchartroddata), #1121.
* **IMPROVEMENT** (by @imaNNeo) Make `drawBehindEverything` property default to `true` in [AxisTitles](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/base_chart.md#axistitle) class, #1097.
* **BUGFIX** (by @imaNNeo) Show `0` instead of `-0` in some edge-cases in the default titles 
* **FEATURE** (by @tamasapps): Add `tooltipHorizontalAlignment` and `tooltipHorizontalOffset` …
=> Bump version to 0.61.0

CHANGELOG.md, lib/src/chart/base/axis_chart/axis_chart_data.dart, lib/src/chart/base/axis_chart/axis_chart_painter.dart, repo_files/documentations/base_chart.md
Resolving issue #1195 
Added gradient attribute to [horizontalRangeAnnotations](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/base_chart.md#horizontalrangeannotation) and [VerticalRangeAnnotation](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/base_chart.md#verticalrangeannotation).
This will help specify gradient or solid color to range annotations. If none were identified, it would use a solid whit color.
=> added gradient color to range annotations, issue #1195.

CHANGELOG.md, example/.metadata, example/windows/CMakeLists.txt, example/windows/runner/CMakeLists.txt, example/windows/runner/flutter_window.cpp, example/windows/runner/main.cpp, example/windows/runner/win32_window.cpp, example/windows/runner/win32_window.h, lib/src/chart/base/axis_chart/axis_chart_data.dart, lib/src/chart/base/axis_chart/axis_chart_painter.dart, lib/src/extensions/bar_chart_data_extension.dart, repo_files/documentations/base_chart.md, test/chart/bar_chart/bar_chart_painter_test.dart, test/extensions/bar_chart_data_extensions_test.dart
1. fix windows build for example app
2. groupSpace also takes effect when alignment is BarChartAlignment.end or BarChartAlignment.start
these aliment would not automatically adjust group spacing, compare to BarChartAlignment.spaceBetween and the like.
3. supports setting line StrokeCap on HorizontalLine/VerticalLine
=> refactor: add some features to BarChart

example/README.md
Just a link typo fix (from github, links without the scheme go to `https://github.com/imaNNeo/fl_chart/blob/master/example/app.flchart.dev`), thanks for the library!
=> Fixed Link on Example Readme

CHANGELOG.md, lib/src/chart/bar_chart/bar_chart_painter.dart, test/chart/bar_chart/bar_chart_painter_test.dart
Added `backDrawRodData`'s y-axis to take in account when calculating pixels.
close #1345
=> Fix: Tooltip not displaying when value from BackgroundBarChartRodData is less than zero

CHANGELOG.md, pubspec.yaml
* **BUGFIX** (by @Anas35) Fix Tooltip not displaying when value from BackgroundBarChartRodData is less than zero. #1345.
* **BUGFIX** (by @imaNNeo) Fix Negative BarChartRodStackItem are not drawn correctly bug, #1347
* **BUGFIX** (by @imaNNeo) Fix bar_chart_helper minY calculation bug, #1388
* **IMPROVEMENT** (by @imaNNeo) Consider fraction digits when formatting chart side titles, #1267
=> Bump version to 0.64.0

CHANGELOG.md, lib/src/chart/line_chart/line_chart_painter.dart
=> Fix bar line shadow crash when we have only one (or zero) spot, #1466

CHANGELOG.md, lib/src/chart/bar_chart/bar_chart_helper.dart, test/chart/bar_chart/bar_chart_helper_test.dart, test/chart/bar_chart/bar_chart_painter_test.dart
* **BUGFIX** (by @imaNNeo) Fix having negative `toY` (or positive `fromY`) in BarChart's `minY` and `maxY` calculations, #1470
=> Fix negative values in BarChart

CONTRIBUTING.md
Remove the changelog section from CONTRIBUTING. Because it is a file which changes by all the users who create a PR, so they get conflict everytime. That's why I decided to handle the CHANGELOG in another way.
=> Remove the changelog section from CONTRIBUTING.

CHANGELOG.md, pubspec.yaml
* **FEATURE** (by @Dartek12) Added gradient to [FlLine](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/base_chart.md#FlLine), #1197
* **BUGFIX** (by @imaNNeo) Fix bar line shadow crash when we have only one (or zero) spot, #1466
* **BUGFIX** (by @imaNNeo) Fix having negative `toY` (or positive `fromY`) in BarChart's `minY` and `maxY` calculations, #1470
* **BUGFIX** (by @bobatsar) Fix bars drawn outside of diagram
* **FEATURE** (by @k0psutin) Add dashed border to BarChartRodData, #1144
* **FEATURE** (by @imaNNeo) Allow to show single point line in LineChart, #1438
=> Bump version to 0.65.0

CHANGELOG.md, pubspec.yaml
=> Add pubspec constraints for newer version of flutter/dart

CHANGELOG.md, lib/src/chart/pie_chart/pie_chart_painter.dart, test/chart/pie_chart/pie_chart_painter_test.dart
=> Fix pieChart drawing single section on iPhone, #1515

lib/src/chart/pie_chart/pie_chart_data.dart, lib/src/chart/pie_chart/pie_chart_painter.dart, repo_files/documentations/pie_chart.md, test/chart/pie_chart/pie_chart_painter_test.dart
rebased pull request as per guidelines
and closing old https://github.com/imaNNeo/fl_chart/pull/1511
=> Add gradient for PieChart

example/android/build.gradle
I am using Android Studio Giraffe | 2022.3.1 Patch 2
when building the fl_chart example, I got an error about Kotlin version. So I upgraded Kotlin version in build.gradle and fl_chart builds and runs fine.
=> Upgrade Kotlin version from 1.6.10 to 1.7.10

lib/src/chart/bar_chart/bar_chart_data.dart, lib/src/chart/line_chart/line_chart_data.dart
The Platform.environment can not be be accessed in flutter web. Remove the check when running on web to prevent an exception.
Fixes #1565.
=> Fix unsupported environment access on web

lib/src/chart/bar_chart/bar_chart_data.dart, lib/src/chart/line_chart/line_chart_data.dart, test/chart/bar_chart/bar_chart_painter_test.dart, test/chart/base/axis_chart/side_titles/side_titles_widget_test.dart, test/chart/line_chart/line_chart_painter_test.dart
This PR is related to issue #1577.
Two classes used dart:io to determine whether the code is being executed as part of a test.
This prevented the usage of fl_chart for the Web as the target platform.
I moved the test-related initialization code from the production code to the unit tests.
=> Removed dependency to dart:io in order to support Web #1577

CHANGELOG.md, example/lib/presentation/samples/bar/bar_chart_sample1.dart, example/lib/presentation/samples/bar/bar_chart_sample2.dart, example/lib/presentation/samples/bar/bar_chart_sample3.dart, example/lib/presentation/samples/bar/bar_chart_sample7.dart, example/lib/presentation/samples/line/line_chart_sample1.dart, example/lib/presentation/samples/line/line_chart_sample3.dart, example/lib/presentation/samples/line/line_chart_sample5.dart, example/lib/presentation/samples/line/line_chart_sample8.dart, example/lib/presentation/samples/line/line_chart_sample9.dart, example/lib/presentation/samples/scatter/scatter_chart_sample2.dart, lib/src/chart/bar_chart/bar_chart_data.dart, lib/src/chart/bar_chart/bar_chart_painter.dart, lib/src/chart/line_chart/line_chart_data.dart, lib/src/chart/line_chart/line_chart_painter.dart, lib/src/chart/scatter_chart/scatter_chart_data.dart, lib/src/chart/scatter_chart/scatter_chart_painter.dart, pubspec.yaml, repo_files/documentations/bar_chart.md, repo_files/documentations/handle_touches.md, repo_files/documentations/line_chart.md, repo_files/documentations/migration_guides/0.67.0/MIGRATION_00_67_00.md, repo_files/documentations/migration_guides/INDEX.md, repo_files/documentations/scatter_chart.md, test/chart/bar_chart/bar_chart_painter_test.dart, test/chart/data_pool.dart, test/chart/line_chart/line_chart_painter_test.dart, test/chart/scatter_chart/scatter_chart_data_test.dart, test/chart/scatter_chart/scatter_chart_painter_test.dart
This PR is to replace this one: https://github.com/imaNNeo/fl_chart/pull/1348.
All credits goes to @apekshamehta
**Changes Made:**
In the bar_chart_data.dart file:
Added a new parameter getTooltipColor to the constructor of BarTouchTooltipData.
Defined a new type GetBarTooltipColor, which is a function that takes a BarChartGroupData parameter and returns a Color.
In the bar_chart_painter.dart file:
Assigned the tooltip color to the _bgTouchTooltipPaint.color property using the getTooltipColor function from the tooltipData object.
Additionally, the getTooltipColor function has been utilized in the bar_chart_sample1.dart file within the feature/dynamic-tooltip-bgcolor branch.
Please review the changes for this pull request.
=> Dynamically changing tooltipBgColor

CHANGELOG.md, pubspec.yaml
* **FEATURE** (by @julien4215) Add direction property to the [HorizontalLineLabel](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/base_chart.md#horizontallinelabel) and [VerticalLineLabel](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/base_chart.md#verticallinelabel), #1574
* **FEATURE**  (by @apekshamehta) Added new method called getTooltipColor for axis charts (bar,line,scatter) to change background color of tooltip dynamically.[issue](https://github.com/imaNNeo/fl_chart/issues/1279).
* **BREAKING** (by @apekshamehta) Removed tooltipBgColor property from Bar, Line and Scatter Charts (you can now use `getTooltipColor` which provides more customizability), checkout the [full migration guide …
=> Bump version to 0.67.0

CHANGELOG.md, lib/src/chart/base/axis_chart/axis_chart_data.dart, lib/src/chart/base/axis_chart/axis_chart_helper.dart, lib/src/chart/base/axis_chart/side_titles/side_titles_widget.dart, repo_files/documentations/base_chart.md, test/chart/base/axis_chart/side_titles/side_titles_test.dart
Including titles (labels) for the minimum and maximum data value is sometimes not desirable (see #906). The iterateThroughAxis routine (in axis_chart_helpers.dart) provides the logic for optional inclusion of the minimum and maximum already. This PR gives users control over these flags by incorporating them into SideTitles.
=> Giving users control over min/maxIncluded for axis titles by including them into SideTitles (addresses #906)

lib/src/utils/utils.dart
Removes the redundant import of 'dart:math'. The package was imported twice, once with an alias and once without. Only the alias import ('dart:math' as math) is kept for clarity and to avoid potential conflicts.
=> Remove redundant import of 'dart:math'

example/linux/CMakeLists.txt
This pull request addresses the issue where the example app in the fl_chart repository fails to build on Linux due to invalid target names in the CMake configuration.
The build process for the Linux platform fails with the following errors:
```
CMake Error at CMakeLists.txt:63 (add_executable):
The target name "FL Chart App" is reserved or not valid for certain CMake
features, such as generator expressions, and may result in undefined
behavior.
CMake Error at CMakeLists.txt:43 (target_compile_features):
Cannot specify compile features for target "FL Chart App" which is not
built by this project.
Call Stack (most recent call first):
CMakeLists.txt:71 (apply_standard_settings)
CMake Error at CMakeLists.txt:74 (target_link_libraries):
Cannot specify link libraries for target "FL Chart App" …
```
=> fix: example app build for Linux (Issue  #1667)

CHANGELOG.md, pubspec.yaml
* **BUGFIX** (by @imaNNeo) Fix a memory leak issue in the axis-based charts, there was a logic to calculate and cache the minX, maxX, minY and maxY properties to reduce the computation cost. But it caused some memory issues, as we don't have a quick solution for this, we disabled the caching logic for now, later we can move the calculation logic to the render objects to keep and update them only when the data is changed, #1106, #1693
* **BUGFIX**  (by @imaNNeo) Fix showing grid lines even when there is no line to show in the LineChart, #1691
* **IMPROVEMENT** (by @sczesla) Allow users to control minIncluded and maxIncluded using SideTitles, #906
* **IMPROVEMENT** (by @elizabethzhenliu) Reverse the touch order in ScatterChart, so now the top spots are touched first, #1675
* **IMPROVEMENT** …
=> Bump version to 0.69.0

example/lib/presentation/samples/pie/pie_chart_sample1.dart, lib/src/chart/pie_chart/pie_chart_painter.dart
solves #1505 
This PR uses the Path.contains instead of complex calculations.
=> Fix miss touched section in Pie Chart

CHANGELOG.md, example/lib/presentation/samples/bar/bar_chart_sample1.dart, example/lib/presentation/samples/radar/radar_chart_sample1.dart, example/lib/presentation/samples/scatter/scatter_chart_sample1.dart, lib/src/chart/bar_chart/bar_chart.dart, lib/src/chart/line_chart/line_chart.dart, lib/src/chart/pie_chart/pie_chart.dart, lib/src/chart/radar_chart/radar_chart.dart, lib/src/chart/scatter_chart/scatter_chart.dart, repo_files/documentations/bar_chart.md, repo_files/documentations/pie_chart.md, repo_files/documentations/scatter_chart.md
Deprecate `swapAnimationDuration` and `swapAnimationCurve` properties to use `curve` and `duration` instead to keep the consistency over the project, #1618
=> Deprecate `swapAnimationDuration` and `swapAnimationCurve` properties

lib/src/chart/pie_chart/pie_chart_data.dart, lib/src/chart/pie_chart/pie_chart_painter.dart, lib/src/chart/pie_chart/pie_chart_renderer.dart
This pull request addresses issues related to #697, #817 and #1632.
- Removed the filter that excluded sections with a value of 0 in `PieChartData`.
- Ensured that `calculateSectionsAngle` does not return NaN values.
- Skipped the rendering of sections with a value of 0.
- Created a custom `badgeWidgetPaint` function to skip the rendering of the `badgeWidget` for sections with a value of 0.
=> Fix section with zero problems in PieChart

test/extensions/bar_chart_data_extensions_test.dart
This PR adds tests for the `BarChartDataExtension.calculateGroupsX` method. 
This increases the test coverage of this file from 94.92% to 100%.
=> test: Add tests for bar chart data extensions

lib/src/chart/pie_chart/pie_chart_data.dart, test/chart/data_pool.dart, test/chart/pie_chart/pie_chart_data_test.dart, test/utils/lerp_test.dart
This PR adds tests for lerp utilities and increases the test coverage from 87.52% to 100%. 
In the process I added `EquatableMixin`, because `PieChartSectionData` with the same `sections` were not considered equal.
As far as tests go, this is a breaking change, because one test case assumed pie chart data to be unequal when their `sections` don't reference the same object, even though the `sections` have the same list elements. 
Please let me know, what you think is the best approach for this for fl_chart.
=> fix!: PieChartSectionData equatable

lib/src/chart/bar_chart/bar_chart_data.dart
This PR fixes a typo in the docstring of `BarChartData`
=> fix: Typo in bar chart data docstring

lib/src/extensions/gradient_extension.dart
This PR refactors `GradientExtension.getSafeColorStops` to improve readability.
It makes sense to merge the tests for this method introduced with  #1787 first, to ensure it's still working as expected.
All of the tests introduced in #1787 are still passing with the refactored code.
=> ref: Improve readability of GradientExtension.getSafeColorStops

.github/workflows/verification.yml
This PR replaces the `test` make target that does not exist with `runTests` to ensure tests are run in the workflow. 
Fixes issue #1791
=> fix: Call correct make target to run tests in verification workflow

repo_files/documentations/line_chart.md
There was a small typo, `TextStyle` instead of `TextAlign`.  This PR fixes it.
=> fix typo in line_chart.md

CHANGELOG.md, example/pubspec.yaml, pubspec.yaml
* **FEATURE** (by @Peetee06) Implemented a 5 years-old feature request about scroll and zoom support in our axis-based charts. Special thanks to @Peetee06 who made it happen, #71
* **IMPROVEMENT** (by @Peetee06) Added functionality to control the transformation of axis-based charts using `FlTransformationConfig` class. You can now enable scaling and panning for `LineChart`, `BarChart` and `ScatterChart` using this class
* **IMPROVEMENT** (by @Peetee06) Added some new unit tests in `bar_chart_data_extensions_test.dart`, `gradient_extension_test.dart` and fixed a typo in `bar_chart_data.dart`
* **BREAKING** (by @Peetee06) Fixed the equatable functionality in our BarChart. We hope it will not affect anything in our chart, but because the behaviour is changed, we marked it as a breaking …
=> Bump fl_chart version up to 0.70.0

example/lib/presentation/samples/line/line_chart_sample12.dart, lib/src/chart/base/axis_chart/axis_chart_scaffold_widget.dart, lib/src/chart/base/axis_chart/transformation_config.dart, repo_files/documentations/handle_transformations.md, test/chart/base/axis_chart/axis_chart_scaffold_widget_test.dart
Allows to disable panning and scaling.
When disabled users cannot scale/pan the chart. Transforming the chart via a `TransformationController` is still possible in this case.
Solves #1818
https://github.com/user-attachments/assets/e1acde03-1c65-4437-b955-d0abb39bc955
=> feat: Allow locking scale/translation state

lib/src/chart/radar_chart/radar_chart_data.dart, lib/src/chart/radar_chart/radar_chart_painter.dart, repo_files/documentations/radar_chart.md
This PR adds the `isMinValueAtCenter` flag to the `RadarChartPainter` class to allow the minimum value to be centered in the RadarChart.
- Fixes #1351 
- Fixes #1442
- Added `isMinValueAtCenter` flag to `RadarChartData`
- Updated `RadarChartPainter` methods to support centering the minimum value when `isMinValueAtCenter` is true
<table>
<tr>
<td><strong>isMinValueAtCenter is false</strong></td>
<td><strong>isMinValueAtCenter is true</strong></td>
</tr>
<tr>
<td><img src="https://github.com/imaNNeo/fl_chart/assets/17955947/5c505453-9ef6-4b79-a03b-2bcf1369d8fe" alt="isMinValueAtCenter is false" width="300"/></td>
<td><img src="https://github.com/imaNNeo/fl_chart/assets/17955947/83ac2f04-f78f-4781-acce-47ea54cf24dc" alt="isMinValueAtCenter is true" width="300"/></td>
</tr>
</table>
=> Add isMinValueAtCenter property to RadarChartData

lib/src/chart/bar_chart/bar_chart_data.dart, lib/src/chart/bar_chart/bar_chart_painter.dart, lib/src/chart/line_chart/line_chart_data.dart, lib/src/chart/line_chart/line_chart_painter.dart, lib/src/chart/scatter_chart/scatter_chart_data.dart, lib/src/chart/scatter_chart/scatter_chart_painter.dart, test/chart/bar_chart/bar_chart_painter_test.dart, test/chart/data_pool.dart, test/chart/line_chart/line_chart_painter_test.dart, test/chart/scatter_chart/scatter_chart_painter_test.dart
**IMPROVEMENT** (by @MattiaPispisa) custom border radius in `BarTouchTooltipData`, `LineTouchTooltipData`, `ScatterTouchTooltipData` #1715
=> custom border radius in BarTouchTooltipData

lib/src/chart/base/axis_chart/axis_chart_scaffold_widget.dart, test/chart/base/axis_chart/axis_chart_scaffold_widget_test.dart
Fixes #1863.
**Changes**
This PR eliminates the post frame function in `AxisChartScaffoldWidget` to calculate the `virtualRect`, instead uses the `constraints` of `LayoutBuilder` and other data available in `_stackWidgets`.
**Testing**
Since there is no need to wait 1 frame for the _zoom_ to be applied, I removed the related `tester.pump` and `expect` function calls.
I removed the `post frame callback checks if widget is mounted` test, as it is not needed anymore afaik.
I am not a 100% sure about changing `updates chart rect after the first frame when controller scale != 1.0` to `Initializes zoomed chart rect when controller scale != 1.0` though, as I don't know the exact purpose of the original test.
=> Fix initial zoom first frame

CHANGELOG.md, example/pubspec.yaml, pubspec.yaml
* **IMPROVEMENT** (by @MattiaPispisa) Add a new property called `BorderRadius tooltipBorderRadius` instead of (deprecated) `double tooltipRoundedRadius` in `BarTouchTooltipData`, `LineTouchTooltipData` and `ScatterTouchTooltipData` #1715
* **FEATURE** (by @frybitsinc) Add `children` property in our [RadarChartTitle](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/radar_chart.md#radarcharttitle), #1840
* **BUGFIX** (by @morvagergely) Fix the initial zoom issue in our scrollable LineChart, #1863
=> Bump version up to 0.71.0

CHANGELOG.md
Adds details of the following breaking change, that was included in the 0.70.1 release, to the changelog:
[https://github.com/imaNNeo/fl_chart/commit/83e4dda1b7669aaac33bea8d773f97b1345e90b9](https://github.com/imaNNeo/fl_chart/commit/83e4dda1b7669aaac33bea8d773f97b1345e90b9)
Fixes part of #1971, although I suspect the release notes themselves in the releases page may need to be manually edited as well, unless there's some automation or repo settings magic going on.
=> Add missing breaking change to 0.70.1 changelog

CHANGELOG.md, pubspec.yaml
* **FEATURE** (by @kamilJ96) Add `gradient` property inside our `BarChartRodStackItem` to be able to render gradient (along with the possibility to render a solid color), #919
* **FEATURE** (by @alettsy) Add `sideTitleAlignment` property in our `AxisTitles` to allow you to control the alignment of side titles (for example show them inside the chart), #1946
* **FEATURE** (by @huanghui1998hhh) Add `gradientArea` property to `LineChartBarData` to allow you to control the scope of gradient effects, #1925
* **FEATURE** (by @alikhavarii13) Add `label` and `labelStyle` properties in our `BarChartRodStackItem` to allow you to show labels on each stack item, #598
* **BREAKING** ⚠️ (by @alikhavarii13) `borderSide` now is a [named parameter](https://dart.dev/language/functions#named-parameters) …
=> Bump version up to 1.1.0
