- example/lib/line_chart/samples/line_chart_sample3.dart
- lib/src/chart/line_chart/line_chart_data.dart
- lib/src/chart/line_chart/line_chart_painter.dart
- repo_files/documentations/line_chart.md
removed `showHorizontalLines` and `showVerticalLines` from `ExtraLinesData`
> swapped HorizontalExtraLines, and VerticalExtraLines definitions.

- lib/src/chart/line_chart/line_chart_painter.dart
formatter skipped this line before
> fix format in linepainter

- lib/src/chart/line_chart/line_chart_painter.dart
> Fix clipToBorder in line chart

- lib/src/chart/bar_chart/bar_chart_data.dart
- lib/src/chart/bar_chart/bar_chart_painter.dart
- lib/src/chart/line_chart/line_chart_data.dart
- lib/src/chart/line_chart/line_chart_painter.dart
- repo_files/documentations/bar_chart.md
- repo_files/documentations/line_chart.md
Reverts imaNNeoFighT/fl_chart#237
> Revert "Added fitInsideVertically support for bar chart and line chart tooltips."

- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/line_chart/samples/line_chart_sample1.dart
- example/lib/line_chart/samples/line_chart_sample3.dart
- example/lib/line_chart/samples/line_chart_sample5.dart
- example/lib/line_chart/samples/line_chart_sample6.dart
- example/lib/line_chart/samples/line_chart_sample8.dart
- lib/src/chart/line_chart/line_chart_data.dart
- lib/src/chart/line_chart/line_chart_painter.dart
- repo_files/documentations/line_chart.md
- test/chart/data_pool.dart
- test/chart/line_chart/line_chart_data_test.dart
I was looking for a way to change the shape of the dots in the same line depending on a value and I couldn't see support for it. So I went ahead and made it myself.
Hopefully you find it useful and can merge it.
It could be easily expanded to use other shapes. 
Let me know if you think I should change anything.
> Added option to change shape of line chart dots

- lib/src/utils/lerp.dart
- lib/src/utils/utils.dart
If I changed the behavior by mistake or anybody disagrees with the refactors, please feel free to tell me.
> Refactor utils code

- README.md
- lib/src/chart/radar_chart/radar_chart_data.dart
- repo_files/documentations/index.md
- repo_files/documentations/radar_chart.md
RadarChart documentation added to  repo_files/documentations/radar_chart.md
> Radar Chart  documented

- lib/src/chart/bar_chart/bar_chart_data.dart
- lib/src/chart/bar_chart/bar_chart_painter.dart
- lib/src/chart/line_chart/line_chart_data.dart
- lib/src/chart/line_chart/line_chart_painter.dart
- repo_files/documentations/bar_chart.md
- repo_files/documentations/line_chart.md
As title says, which is a feature I need. Added to both Line and Bar chart.
> Add TextAlign to tooltip.

- .github/workflows/check_code_style_pull_request.yml
- .github/workflows/check_code_style_push.yml
This GitHub action should help you to check the style on formatting on Pull Request. It will post a comment and highlight in the code changes the issues found by `dart analyze` and `dart format`
> Code style check on pull request

- example/lib/bar_chart/samples/bar_chart_sample3.dart
- example/lib/pie_chart/samples/pie_chart_sample3.dart
As null safety is now de-facto branch most users are using, the examples should work on it out-of-the-box.
> Migrated the third PieChart example to null safety

- repo_files/documentations/radar_chart.md
fixed the broken link to the sample radar chart.
> fixed broken link for radar chart sample

- CHANGELOG.md
- lib/src/chart/line_chart/line_chart_data.dart
- lib/src/chart/line_chart/line_chart_painter.dart
- lib/src/chart/scatter_chart/scatter_chart_data.dart
- lib/src/chart/scatter_chart/scatter_chart_painter.dart
Apply #679 changes to all other Axis based charts (Scatter, Line)
> Add rotateAngle property in LineTouchTooltipData

- lib/src/chart/pie_chart/pie_chart_painter.dart
> added _calculateCenterRadius to _drawCenterSpace to fix crash in html renderer

- example/lib/bar_chart/samples/bar_chart_sample3.dart
I remade it.
https://github.com/imaNNeoFighT/fl_chart/pull/742
I'm sorry I made your inconvenience but please check it again!
> Refactoring bar chart sample 3

- lib/src/chart/line_chart/line_chart_painter.dart
> Fix below/above area data transparency issue, #770.

- lib/src/utils/utils.dart
- test/utils/utils_test.dart
> Fix interval below one, #811

- lib/src/chart/bar_chart/bar_chart_painter.dart
- lib/src/chart/base/axis_chart/axis_chart_data.dart
- lib/src/chart/line_chart/line_chart_painter.dart
- lib/src/chart/scatter_chart/scatter_chart_painter.dart
- repo_files/documentations/base_chart.md
Hi, I've decided to take matters into my own hands and add feature requested in #784
> Add side titles text align #784

- CHANGELOG.md
- lib/src/chart/line_chart/line_chart_helper.dart
- test/chart/line_chart/line_chart_helper_test.dart
> Fix `FlSpot.nullSpot` at the first of list bug, #912.

- CHANGELOG.md
- lib/src/chart/base/axis_chart/axis_chart_extensions.dart
- lib/src/chart/line_chart/line_chart_painter.dart
- test/chart/base/axis_chart_extensions_test.dart
> Add axis_chart_extension to handle splitByNullSpots() logic

- CHANGELOG.md
- lib/src/chart/scatter_chart/scatter_chart_painter.dart
> Sort Scatter Spots with radius.

- CHANGELOG.md
- lib/src/chart/line_chart/line_chart_data.dart
- lib/src/chart/line_chart/line_chart_painter.dart
- repo_files/documentations/line_chart.md
This pull request adds the possibility to set the line join from miter to round.
> Add possibility to set line join

- CHANGELOG.md
- example/linux/flutter/generated_plugins.cmake
- example/windows/flutter/generated_plugins.cmake
- lib/src/chart/pie_chart/pie_chart.dart
- pubspec.yaml
> Upgrade to Flutter 3

- CHANGELOG.md
- lib/src/chart/bar_chart/bar_chart.dart
- lib/src/chart/line_chart/line_chart.dart
- lib/src/chart/scatter_chart/scatter_chart.dart
Fixes #987
Check [this gist](https://gist.github.com/imaNNeoFighT/678d5bdfb31421f133c404c1d7be60b2).
https://user-images.githubusercontent.com/7009300/168181809-0164b953-9a5e-4208-989c-4a957ff161f4.mov
> Add 'chartRendererKey' property to LineChart, BarChart, and ScatterChart

- CHANGELOG.md
- pubspec.yaml
* **IMPROVEMENT** Fix test coverage problem
> Bump version to 0.50.4

- CHANGELOG.md
- pubspec.yaml
* **IMPROVEMENT** Fix test coverage problem again :/
> Bump version to 0.50.5

- CHANGELOG.md
- lib/src/utils/utils.dart
https://user-images.githubusercontent.com/7009300/170143281-e18b1e45-660e-4074-8bc5-060e947e8476.mp4
> Fix interval issue on small sizes, #909

- CHANGELOG.md
- lib/src/chart/bar_chart/bar_chart_data.dart
- lib/src/chart/bar_chart/bar_chart_painter.dart
- lib/src/chart/line_chart/line_chart_data.dart
- lib/src/chart/line_chart/line_chart_painter.dart
- lib/src/chart/scatter_chart/scatter_chart_data.dart
- lib/src/chart/scatter_chart/scatter_chart_painter.dart
- repo_files/documentations/bar_chart.md
- repo_files/documentations/line_chart.md
- repo_files/documentations/scatter_chart.md
- test/chart/bar_chart/bar_chart_data_test.dart
- test/chart/bar_chart/bar_chart_painter_test.dart
- test/chart/data_pool.dart
- test/chart/line_chart/line_chart_data_test.dart
- test/chart/line_chart/line_chart_painter_test.dart
- test/chart/scatter_chart/scatter_chart_data_test.dart
Add tooltipBorder property in LineTouchTooltipData, BarTouchTooltipData, ScatterTouchTooltipData
Hello @imaNNeoFighT ! 
I just did what you told me to do and this is my new branch I hope it will work :)
_-- I just saw that on master the test 'Counter increments smoke test' does not pass --_
> Feature - Border for Tooltip 2 (Issue: #692)

- example/lib/bar_chart/samples/bar_chart_sample2.dart
update bottomTitles method to create bottom titles  without  switch cases.
> update bottomTitles method

- analysis_options.yaml
- lib/src/chart/bar_chart/bar_chart.dart
- lib/src/chart/line_chart/line_chart.dart
- lib/src/chart/pie_chart/pie_chart.dart
- lib/src/chart/radar_chart/radar_chart.dart
- lib/src/chart/scatter_chart/scatter_chart.dart
- test/chart/base/axis_chart/axis_chart_scaffold_widget_test.dart
- test/chart/base/axis_chart/side_titles/side_titles_widget_test.dart
- test/chart/data_pool.dart
- test/chart/line_chart/line_chart_painter_test.dart
- test/chart/pie_chart/pie_chart_helper_test.dart
- test/chart/radar_chart/radar_chart_painter_test.dart
- test/utils/list_wrapper_test.dart
[Enabling stricter type checks](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks)
> lint: Enabling stricter type checks

- lib/src/chart/base/axis_chart/side_titles/side_titles_widget.dart
- test/chart/base/axis_chart/side_titles/side_titles_widget_test.dart
> Allow to pass empty barGroups in BarChartData

- CHANGELOG.md
- pubspec.yaml
* **BUGFIX** (by @imaNNeoFighT): Fix inner border of pieChart with single section, #1089
* **IMPORTANT** **IRAN NEEDS HELP**
As you might know, Islamic Republic of Iran is murdering people in silence right now in Iran
They shut the Internet down to do that. That’s why I cannot maintain this library for a while.
Now we need your help, please be our voice by spreading news in your media to support us
Search these hashtags:
[#MahsaAmini](https://twitter.com/search?q=%23MahsaAmini&src=typeahead_click)
[مهسا_امینی](https://twitter.com/search?q=%23%D9%85%D9%87%D8%B3%D8%A7_%D8%A7%D9%85%DB%8C%D9%86%DB%8C&src=typeahead_click&f=top)
[OpIran](https://twitter.com/search?q=%23OpIran&src=typeahead_click&f=top)
Also, [this article](https://www.bbc.com/news/world-middle-east-62984076) might help.
> Bump version to 0.55.2

- example/lib/bar_chart/samples/bar_chart_sample3.dart
fix mistake value BarChar sample source.
issue #1138
> chore : replace the wrong value in BarChart samples

- lib/src/chart/bar_chart/bar_chart_data.dart
> Fixes documentation of `BarChartGroupData` to avoid misunderstandings

- CHANGELOG.md
- lib/src/chart/line_chart/line_chart_painter.dart
> Fix indicator out of range error in line chart

- pubspec.yaml
Today we are able to add some screenshots to be shown on the [pub.dev ](pub.dev)website. 
Check the article about this release [here](https://medium.com/dartlang/screenshots-and-automated-publishing-for-pub-dev-9bceb19edf79), and read about the screenshots [here](https://dart.dev/tools/pub/pubspec#screenshots).
<details>
<summary>We are going to show this screenshots and descriptions, click to see them.</summary>
</details>
> Update pubspec.yaml to support screenshots

- lib/src/chart/line_chart/line_chart_helper.dart
Created another PR to fix rebase issue.
Continue of #1142
> fixed a bug where the chart can not be drawn when one of the line spots are empty.

- CHANGELOG.md
- repo_files/documentations/bar_chart.md
- repo_files/documentations/line_chart.md
- repo_files/documentations/migration_guides/0.50.0/MIGRATION_00_50_00.md
- repo_files/documentations/pie_chart.md
- repo_files/documentations/radar_chart.md
- repo_files/documentations/scatter_chart.md
> Update chart samples url

- .github/workflows/gh-pages.yml
- example/CNAME
[app.flchart.dev](app.flchart.dev)
> Add gh-pages.yml workflow to build the example app to run in app.flchart.dev

- CHANGELOG.md
- lib/src/chart/radar_chart/radar_chart_painter.dart
- test/chart/radar_chart/radar_chart_painter_test.dart
Resolves #1078
This pr solves the problem described in the above issue. The code is taken from a closed pr #1084 as the pr was not merged due to conflicts.
> BugFix: fix radar chart tick point not scaling

- CHANGELOG.md
- lib/src/chart/scatter_chart/scatter_chart.dart
> Fix ScatterChart long-press interaction bug

- repo_files/documentations/line_chart.md
Wrong linking in "FlSpot" fixed. It now redirects to base chart.
> docs wrong link fix

- repo_files/documentations/handle_animations.md
> chore(handle_animations.md):replace = with :

- repo_files/documentations/bar_chart.md
I updated the Bar_Chart_Data to fix the documentation issue #1608. 
The fix is an update of the default value of the  alignment in BarChartData.
> Update bar_chart.md to fix #1608

- CHANGELOG.md
- pubspec.yaml
* **IMPROVEMENT** (by @imaNNeo) Fix the analyzer warnings (to have maximum score in the [pub.dev](https://pub.dev/packages/fl_chart/score))
> Bump version up to 0.69.2

- test/extensions/gradient_extension_test.dart
This PR adds tests for the gradient extension.
It increases test coverage for this file from 0% to 100%.
> test: Add tests for gradient extension

- .github/workflows/codecov.yml
I just updated the workflow to v5 and changed the branch name from `master` to `main` in the codecov settings
I'm not sure which one fixed the issue, but it is fixed now xD
> Code coverage rate limit

- analysis_options.yaml
- lib/fl_chart.dart
- lib/src/chart/bar_chart/bar_chart_data.dart
- lib/src/chart/bar_chart/bar_chart_helper.dart
- lib/src/chart/base/axis_chart/axis_chart_data.dart
- lib/src/chart/base/axis_chart/axis_chart_painter.dart
- lib/src/chart/base/custom_interactive_viewer.dart
- lib/src/chart/line_chart/line_chart_data.dart
- lib/src/chart/line_chart/line_chart_helper.dart
- lib/src/chart/pie_chart/pie_chart.dart
- lib/src/chart/pie_chart/pie_chart_painter.dart
- lib/src/chart/scatter_chart/scatter_chart_data.dart
- lib/src/utils/path_drawing/dash_path.dart
- pubspec.yaml
- test/chart/line_chart/line_chart_painter_test.dart
Upgraded all the dependencies including the `very_good_analysis` #1809
> Upgrade all the dependencies

- CHANGELOG.md
- example/pubspec.yaml
- pubspec.yaml
* **FEATURE** (by @Peetee06) Add `panEnabled` and `scaleEnabled` properties in the TransformationController, #1818
* **FEATURE** (by @mitulagr2) Add `renderPriority` feature in our [ScatterSpot](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/scatter_chart.md#scatterspot), #1545
* **FEATURE** (by @imaNNeo) Add `rotationQuarterTurns` property in our Axis-Based charts (such as [LineChart](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/line_chart.md), [BarChart](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/bar_chart.md) and [ScatterChart](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/scatter_chart.md)). It allows you to rotate the chart 90 degrees (clockwise) in each turn. For example you …
> Bump version up to 0.70.1

- lib/src/chart/radar_chart/radar_chart_data.dart
- lib/src/chart/radar_chart/radar_chart_painter.dart
since its been a while I synced main branch 
I created new branch and reapplied the diffs @imaNNeo 
(this was my outdated pr :  https://github.com/imaNNeo/fl_chart/pull/1718)
> add text span to RadarChart

- lib/src/chart/bar_chart/bar_chart_data.dart
- lib/src/chart/line_chart/line_chart_data.dart
- lib/src/chart/scatter_chart/scatter_chart_data.dart
- test/chart/bar_chart/bar_chart_painter_test.dart
> Fix format

- CHANGELOG.md
- pubspec.yaml
> Update the flutter and dart sdk constraints

- example/lib/cubits/app/app_cubit.dart
- example/lib/cubits/app/app_state.dart
- example/lib/presentation/pages/home_page.dart
- example/lib/presentation/widgets/download_native_app_button.dart
- example/lib/urls.dart
- example/macos/Flutter/GeneratedPluginRegistrant.swift
> Add DownloadNativeAppButton UI
